language: go

go:
  - 1.1
  - 1.2
  - release
  
install:
    - go get code.google.com/p/go.text/encoding
    - go get code.google.com/p/go.net/ipv4
    - go get github.com/miekg/dns

script:
 - export GOPATH=$TRAVIS_BUILD_DIR:$GOPATH
 - go test -v ./...
